version: '3.8'

services:
  api-desperdicio:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DatabaseConnection=Host=db;Port=5432;Database=esgdb;Username=user;Password=password
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      db:
        condition: service_healthy
    networks:
      - esg-network
    container_name: api-desperdicio-1

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: esgdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - esg-network
    container_name: db-1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d esgdb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 20s

networks:
  esg-network:
    driver: bridge

volumes:
  postgres_data:
