// <auto-generated />
using System;
using Fiap.Web.Api.Desperdicio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fiap.Web.Api.Desperdicio.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fiap.Web.Api.Desperdicio.Models.Alimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Doado")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("QuantidadeKg")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("alimentos", (string)null);
                });

            modelBuilder.Entity("Fiap.Web.Api.Desperdicio.Models.Impacto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Co2EconomizadoKg")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalKgReaproveitados")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRefeicoesGeradas")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("impactos", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
